// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AppProvider: typeof import('./../src/components/Application/src/AppProvider.vue')['default']
    BasicMenu: typeof import('./../src/components/Menu/src/BasicMenu.vue')['default']
    BasicSubMenuItem: typeof import('./../src/components/Menu/src/components/BasicSubMenuItem.vue')['default']
    Menu: typeof import('./../src/components/SimpleMenu/src/components/Menu.vue')['default']
    MenuItem: typeof import('./../src/components/SimpleMenu/src/components/MenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleMenu: typeof import('./../src/components/SimpleMenu/src/SimpleMenu.vue')['default']
    SimpleSubMenu: typeof import('./../src/components/SimpleMenu/src/SimpleSubMenu.vue')['default']
    SubMenuItem: typeof import('./../src/components/SimpleMenu/src/components/SubMenuItem.vue')['default']
  }
}

export {}
